### ISSUE TITLE
canvas.querySelector is not a function

### ISSUE THREAD

**Issue by matart15** [storybookjs/testing-library#14]
can't use all testing-library functions

**Comment by yannbf** [comment]
Hey @matart15 thanks for opening this issue. I believe you might not be using testing library correctly.
The result from `within(canvasElement)` gives you queries that return `HTMLElement`, and the `HTMLElement` is the one that supports `querySelector`.

Example:
```
// wrong
const canvas = within(canvasElement)
const someElement = canvas.querySelector('.vip') // does not exist

// right
const canvas = within(canvasElement)
const container = canvas.getByTestId('container')
const someElement = container.querySelector('.vip') // works!
```

**Comment by matart15** [comment]
Oh I see.  Thank you.
