### ISSUE TITLE
[Bug] UserEvent - Hover not working in NextJS Storybook - Interactive stories - Play function

### ISSUE THREAD

**Issue by Bernard-Grabyo** [storybookjs/testing-library#16]
### Describe the bug

I have a basic story for a Next.JS page. I want to use the `userEvent.hover` method in a `play` method of an interactive story.

### Steps to reproduce the behavior

1. Run `npx create-next-app@latest storybook`.
2. Run `cd storybook`.
3. Run `npx sb init --builder webpack5`.
4. Change the `eslintrc.json` `extends` to include `plugin:storybook/recommended`
```
{
  "extends": ["next/core-web-vitals", "plugin:storybook/recommended"]
}
```
5. Add `data-testid="documentation"` to a link in the `storybook/pages/index.js` file.
```
<a
  href="https://nextjs.org/docs"
  className={styles.card}
  data-testid="documentation"
>
  <h2>Documentation &rarr;</h2>
  <p>Find in-depth information about Next.js features and API.</p>
</a>
```
6. Create a story in `storybook/stories` for the page.
```
import Home from "../pages/index";
import { within, userEvent } from "@storybook/testing-library";

export default {
  title: "Pages/Home",
  component: Home,
};

export const HomePage = () => <Home />;

HomePage.play = async ({ canvasElement }) => {
  const canvas = within(canvasElement);

  const node = canvas.getByTestId(/documentation/i);

  // Should trigger a visual change from the CSS.
  await userEvent.hover(node);
};
```

### Expected behavior

The CSS hover classes should be applied to the link

### Screenshots and/or logs
<img width="1438" alt="Screenshot 2022-03-24 at 17 36 36" src="https://user-images.githubusercontent.com/83646953/159976778-aeb22019-13bf-4cf0-9aaa-33fb10292f0d.png">

Image above: The interaction played. But there is no visual change to the link. It should show the hover state.

<img width="1437" alt="Screenshot 2022-03-24 at 17 41 32" src="https://user-images.githubusercontent.com/83646953/159977529-1725d558-67fe-40bb-8eca-09689504a942.png">

Image above: The hover state being manually triggered by using the Web Inspector in Google Chrome.

### Environment

 - OS: Mac OSX  Monterey 12.1
 - Node.js version: v12.22.3
 - NPM version: 6.14.13
 - Browser (if applicable): chrome
 - Browser version: Version 99.0.4844.83 (Official Build) (x86_64)

**Comment by Bernard-Grabyo** [comment]
@domyen @theinterned @marchdoe @orta @arunoda apologies for pasting you all, but are any of you able to replicate this issue? I'm hoping I've missed something or made a mistake.

**Comment by domyen** [comment]
@Bernard-Grabyo please don't `@mention` maintainers and contributors – not all of us work on the same part of Storybook or it's integrations. 

The hover event doesn't simulate CSS styles (not possible). This is not a Storybook issue, there is no browser API to trigger this with JavaScript.
