### ISSUE TITLE
[Bug] Storybook Interaction "play" method triggers before component is ready?

### ISSUE THREAD

**Issue by danielthedifficult** [storybookjs/testing-library#25]
### Describe the bug

```await expect(canvas.getByTestId('welcome-text')).toBeInTheDocument(); ``` fails, citing that it can't find that element.

If I enter ```$('[data-testid="welcome-text"]')``` into the console to try to find it, it works fine, finds the element no problem.

### Expected behavior

I would expect it to find the element.

For what it's worth, I have tried skipping the custom selector I'm setting up with ```configure({ testIdAttribute: 'data-name' });```

### Screenshots and/or logs

See comments below.

### Environment

 - OS: Mac OS Big Sur
 - Node.js version: 14.18
 - NPM versions:
    "@storybook/addon-actions": "^6.3.12",
    "@storybook/addon-essentials": "^6.3.12",
    "@storybook/addon-interactions": "^6.5.6",
    "@storybook/addon-links": "^6.3.12",
    "@storybook/addon-viewport": "^6.5.6",
    "@storybook/cli": "^6.4.22",
    "@storybook/jest": "^0.0.10",
    "@storybook/node-logger": "^6.3.12",
    "@storybook/preset-create-react-app": "^3.2.0",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/react": "^6.3.12",
    "@storybook/test-runner": "^0.1.1",
    "@storybook/testing-library": "^0.0.11",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",

 - Browser (if applicable): Brave 
 - Browser version (if applicable): 1.40.107 Chromium: 103.0.5060.53 (Official Build) (x86_64) 

### Additional context

https://user-images.githubusercontent.com/1290033/177137405-20144af6-3b24-4357-a34e-73bf46e66077.mov

```
export const SignupInteractions: StoryObj<UIParams> = {
	render: Template,
	args: { ...SignupDefaultUI.args },
	parameters: {
		chromatic: {
			disableSnapshot: true,
		},
	},
	async play({ canvasElement }): Promise<void> {
		const canvas = within(canvasElement);
		configure({ testIdAttribute: 'data-name' });

		await expect(canvas.getByTestId('welcome-text')).toBeInTheDocument(); << This FAILS

...etc...

```

Storybook error: 
```
TestingLibraryElementError: Unable to find an element by: [data-name="welcome-text"]

Ignored nodes: comments, <script />, <style />
<div
  id="root"
>
  <div
    style="outline: red dotted 2px; outline-offset: -2px;"
  >
    <div
      style="display: flex; align-items: center; justify-content: center; min-height: 98.55vh; flex-direction: column;"
    />
  </div>
</div>
```

But the element is clearly in the DOM....
<img width="1739" alt="Screen Shot 2022-07-04 at 2 20 37 PM" src="https://user-images.githubusercontent.com/1290033/177153895-fb2c77fc-267c-4195-ae1f-5ee0fdf8cce4.png">

**Comment by danielthedifficult** [comment]
Updating, as I believe the 'can't find until I inspect' behavior is just the [automatic console targeting happening when inspecting.](https://stackoverflow.com/questions/44018019/javascript-chrome-console-cant-find-element-until-after-i-inspect-it)

The original issue remains- my test code:
```
export const SignupInteractions: StoryObj<UIParams> = {
	render: Template,
	args: { ...SignupDefaultUI.args },
	parameters: {
		chromatic: {
			disableSnapshot: true,
		},
	},
	async play({ canvasElement }): Promise<void> {
		const canvas = within(canvasElement);
		configure({ testIdAttribute: 'data-name' });

		await expect(canvas.getByTestId('welcome-text')).toBeInTheDocument(); << This FAILS

...etc...

```

Storybook error: 
```
TestingLibraryElementError: Unable to find an element by: [data-name="welcome-text"]

Ignored nodes: comments, <script />, <style />
<div
  id="root"
>
  <div
    style="outline: red dotted 2px; outline-offset: -2px;"
  >
    <div
      style="display: flex; align-items: center; justify-content: center; min-height: 98.55vh; flex-direction: column;"
    />
  </div>
</div>
```

But the element is clearly in the DOM....
<img width="1739" alt="Screen Shot 2022-07-04 at 2 20 37 PM" src="https://user-images.githubusercontent.com/1290033/177153895-fb2c77fc-267c-4195-ae1f-5ee0fdf8cce4.png">

**Comment by danielthedifficult** [comment]
Hello, apologies for the delayed reply.

I figured out that the mysterious inability to find the element via the console was that it was set to the wrong context. When clicking + inspecting, I was focusing the storybook iframe as the context, then it was able to find it.

The original problem of Storybook interactions being not able to find the element remains, howeve.r..

**Comment by danielthedifficult** [comment]
@yannbf may your children be blessed with happy, beautiful and wealthy parents.

I am very new to Storybook interaction testing, and it's true that coming from Cypress.io I am used to having methods that retry before timing out. Indeed, switching from getBy to findBy gave the component a few extra cycles to render (it renders after an async api call to get the content to render).

Is there a better way to wait for things to settle before starting a battery of tests? From your docs 
> The [play](https://storybook.js.org/docs/react/writing-stories/play-function) function is a small snippet of code that runs **after a story finishes rendering.** 

My component code (the component that is rendered in the story):
`export const SignupPage = ({ signupID }: SignupPageProps) => {

// async custom Reach hook that fetches a particular signup form's parameters (like custom welcome text, etc.) and returns it to the component.
	const signupSettings = useSignup(signupID);

// I return null until the async settings are fetched.
	return signupSettings ? (
		<Page>
			<PageHeader>
				<h1>Signup</h1>
			</PageHeader>
			<SignUp {...signupSettings} />
			<PageFooter> </PageFooter>
		</Page>
	) : null;
};
`

Will the play sequence run/trigger if the component returns null?

**Comment by IanVS** [comment]
@danielthedifficult I think in this situation using one of the async matchers (like findBy) is the correct solution.  The play function _is_ executing after the render, it's just that the first render of your component returns null.  There's not really a way for the play function to be aware of what logic is happening inside your component and know whether it should wait to execute until some other async logic completes.

**Comment by danielthedifficult** [comment]
Roger that.

The alternative would be to await and not return anything (including null) until the component renders fully... and that doesn't seem like a great idea. 

It's working with FindBy so I'm happy with that. Thank you as always to the amazing storybook team.
