### ISSUE TITLE
[Request] Support user-event v14

### ISSUE THREAD

**Issue by minop1205** [storybookjs/testing-library#26]
testing-library/user-event@13 is not maintained, are there any plans to update it to v14?

**Comment by ysulyma** [comment]
I need this in order to [select text](https://testing-library.com/docs/user-event/pointer#selectiontarget) in my interactions.

**Comment by pushred** [comment]
There is an upstream blocker on this apparently, see: https://github.com/storybookjs/testing-library/pull/19#issue-1210742601

Would be good for @yannbf to provide more details about that blocker. Also perhaps separate releases per framework need to be made if this blocker will exist much longer? In my case I need both this and the fix in #23 that currently exists only in the `next` release. I suppose a fork is warranted but there is overhead going that route in my org. More context/timing would be helpful so I can weigh forking vs. workaround debt.

**Comment by loyaj** [comment]
I too have come across the need to use something introduced in `user-event` v14, specifically the Pointer API. Do we know if the upstream issue in `user-event` has been addressed? (A link to the blocking issue would be helpful as well)

**Comment by yannbf** [comment]
Hey everyone! Thanks a lot for your patience. 
The prior issues have been addressed and [@storybook/testing-library v0.2.0](https://github.com/storybookjs/testing-library/releases/tag/v0.2.0) has been released with upgraded versions of user-event and testing-library/dom. Please give it a try and let us know if you encounter any problems!
