### ISSUE TITLE
[Bug] userEvent not returning a promise

### ISSUE THREAD

**Issue by realappie** [storybookjs/testing-library#40]
### Describe the bug

Im confused, the docs seem to be using async/await when using `userEvent`. See [docs](https://storybook.js.org/docs/react/writing-stories/play-function) but when trying this locally, there is no promise returned by `userEvent` methods

<img width="790" alt="image" src="https://github.com/storybookjs/testing-library/assets/10495548/15760701-ec91-428c-9d1e-eeed56c3ce72">

### Steps to reproduce the behavior

I have a situation where Im typing something in a input field, followed by a click on the submit button. I expect the form submission to fire but its not working. For now I have resorted to `waitFor` which leads me to believe theres a timing issue. 

Now I _think_ being able to `await` the clicking of the button would solve this, which lead me down this rabbit hole of figuring out whether you support it or not. The story looks something like this

```typescript
export const FormSubmitNumericValue: ComponentStoryObj<typeof NumberInputField> = {
    play: async () => {
        userEvent.clear(screen.getByRole('textbox'));
        userEvent.type(screen.getByRole('textbox'), '2');

        userEvent.click(
            screen.getByRole('button', {
                name: 'Submit',
            }),
        );

        // expect(onSubmit).toBeCalledWith({ numericField: 2 }); <-- this does not work

        waitFor(() => {
            expect(onSubmit).toBeCalledWith({ numericField: 2 }); // <--- this works
        });
    },
};
```

### Expected behavior

Either revising the docs and removing `await` keyword or ensuring it works in this package by perhaps upgrading to `@testing-library/user-event` **v14** which I think would translate into supporting async user events as the API became promise based (see [release notes](https://github.com/testing-library/user-event/releases/tag/v14.0.0))

Im not sure if the timing issue is something with my setup, or the userEvent API has a bug. The docs showing the `await` keyword led me to open this issue to get clarification. 

### Environment
Im using @storybook/testing-library `v0.0.13` but latest version (0.1.0) seems to be on same version of the "@testing-library/user-event"

**Comment by ramishenouda48** [comment]
was just about to report the same issue

**Comment by yannbf** [comment]
Hey everyone! Thanks a lot for this issue. Even though it's counter intuitive, this library is actually instrumented and everything is indeed a promise, even though the types didn't match.
 
However, [@storybook/testing-library v0.2.0](https://github.com/storybookjs/testing-library/releases/tag/v0.2.0) has been released with upgraded versions of user-event and testing-library/dom which should fix this issue. Please give it a try and let us know if you encounter any problems!
