### ISSUE TITLE
[Bug] Testing if an element doesn't exists throw an erro

### ISSUE THREAD

**Issue by guimaferreira** [storybookjs/testing-library#42]
### Describe the bug
_(I don´t know if it´s a bug or an expected behavior, but I couldn´t find any docs about it.)_

When  I'm trying to test if an element doesn't exist, I get the error:
```
within(<div#storybook-root>).getByText("Loading Messages...")
Unable to find an element with the text: Loading Messages.... This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
See the full stack trace in the browser console.
```

### Steps to reproduce the behavior

``` Typescript
// Component
return (
    <div
      id="test"
      ref={chatMessagesRef}
      className="flex flex-col overflow-y-auto"
      data-testid="Messages"
    >
      {messages.length ? (
        messages?.map((message, key) => <Message {...message} key={key} />)
      ) : (
        <div>Loading Messages...</div>
      )}
    </div>
  );
```

``` Typescript
export const Default: Story = {
  args,
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    const messages = await canvas.findByTestId("Messages");
    const loading = await canvas.getByText("Loading Messages...");
  },
};
```

### Expected behavior

It should not throw an error and let me use `expect` to test if it exists.
I already tried wrapping in a `try catch`, but it doesn´t work.
Also I couldn´t find on the internet neither on the docs how to test if an element doesn´t exists.

This is important to ensure something that should not be rendered, isn´t rendered.

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment
I tested in these environments:
 - Mac OS Ventura 13.3.1. Node.js v18.15.0
 - Windows 11. Node.js v16.19.0
 - Both with `"@storybook/testing-library": "^0.1.0"`

### Additional context

If this isn´t a bug, maybe it´s a good idea to document how to test unexisting elements.

**Comment by caribouflex** [comment]
I believe your issue is the same as what is mentioned in this [one](https://github.com/testing-library/jest-dom/issues/202). 

I got the same problem yesterday and I ended up applying this [comment](https://github.com/testing-library/jest-dom/issues/202#issuecomment-671132519).

**Comment by guimaferreira** [comment]
Thanks, @caribouflex , that solved it for me also.
